genpolicy: reject create custom hook settings
kata-containers/kata-containers pull request #10075
Opened 2024-07-25 20:36 UTC by Redent0r

Cherry pick from https://github.com/microsoft/kata-containers/pull/140

2024-07-26 16:10 UTC, danmihai1 requested changes

2024-07-26 16:10 UTC, danmihai1 commented on src/tools/genpolicy/rules.rego
> +    is_null(i_oci.Hooks)
@Redent0r , we already have this rule in allow_create_container_input() nowadays.

2024-08-02 20:13 UTC, danmihai1 approved these changes

2024-08-02 21:36 UTC, GabyCT approved these changes

2024-08-02 21:36 UTC, merged