Forward port annotation doc
kata-containers/kata-containers pull request #1045
Opened 2020-10-28 15:45 UTC by c3d

Forward port annotation documentation fixes from
https://github.com/kata-containers/documentation/pull/755
https://github.com/kata-containers/documentation/pull/757

2020-10-28 16:08 UTC, devimc requested changes
thanks @c3d

2020-10-28 16:09 UTC, devimc approved these changes

2020-10-28 16:25 UTC, jodh-intel approved these changes
Thanks @c3d.

2020-11-09 10:47 UTC, c3d commented
There is a spell-check failure on parts I did not change:

```
15444INFO: Spell checking file 'docs/how-to/how-to-load-kernel-modules-with-kata.md'
15445WARNING: Word 'configurated': did you mean one of the following?: configuration, reconfigured, Confederate, confederate
15446WARNING: Word 'cri': did you mean one of the following?: cir, crib, chi, cry, Fri, crier
15447ERROR: Spell check failed for file: 'docs/how-to/how-to-load-kernel-modules-with-kata.md'
15448INFO: spell check failed for document docs/how-to/how-to-load-kernel-modules-with-kata.md
15449INFO: Spell checking file 'docs/how-to/how-to-set-sandbox-config-kata.md'
15450INFO: Spell check successful for file: 'docs/how-to/how-to-set-sandbox-config-kata.md'
15451ERROR: spell check failed, See https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md#spelling for more information.
```

I will fix the failures.

2020-11-10 10:05 UTC, c3d commented
/test

2020-11-10 10:34 UTC, merged