runtime: clh: disable virtiofs DAX when FS cache size is 0
kata-containers/kata-containers pull request #1101
Opened 2020-11-11 16:47 UTC by devimc

Guest consumes 120Mb more of memory when DAX is enabled and the default
FS cache size (8G) is used. Disable dax when it is not required
reducing guest's memory footprint.

Without this patch:

```
7fdea4000000-7fdee4000000 rw-s 18850589 /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              187876 kB
```

With this patch:

```
7fa970000000-7fa9b0000000 rw-s 612001  /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               57308 kB
Pss:               56722 kB
```

fixes #1100

Signed-off-by: Julio Montes <julio.montes@intel.com>

-------

cc @likebreath

2020-11-11 17:49 UTC, fidencio approved these changes
lgtm, @devimc! Thanks!

2020-11-11 18:34 UTC, likebreath commented
/test

2020-11-11 19:05 UTC, likebreath requested changes
@devimc Thanks again for finding and fixing the issue here. The data looks great. Besides one comments above, I think you will also need to update the version of cloud-hypervisor to get generate the the new OpenApi client code before your patch will work (as you found, `dax=false` will be ignored by the current client code).

2020-11-11 19:05 UTC, likebreath commented on src/runtime/virtcontainers/clh.go
> +	}
I think we got a conflict here, when we have both `VirtioFSCacheSize = 0` and `virtioFsCacheAlways`. This is also a bug in the original implementation, but it was `working` as `VirtioFSCacheSize = 0` will be omitted when the struct is serialized to json stream (and clh will use its default `VirtioFSCacheSize` value that is 8G.).

My understanding is `VirtioFSCacheSize` got higher priority than `VirtioFSCache` in our kata configuration file, 
given the way how we disable DAX in kata w/ qemu is merely setting `VirtioFSCacheSize = 0` (regardless of the cache mode). If my understanding is right, I'd suggest to remove this block, and always assign `cacheSize =: int64(clh.config.VirtioFSCacheSize << 20)` .

2020-11-11 20:38 UTC, devimc commented
@likebreath fixed, please take a look, thanks

2020-11-11 20:42 UTC, devimc commented
/test

2020-11-12 15:34 UTC, devimc commented
/test

2020-11-12 17:48 UTC, likebreath approved these changes

2020-11-12 17:48 UTC, likebreath commented
/test-vfio

2020-11-12 20:26 UTC, merged