kata-deploy: stop mentioning qemu-virtiofsd, as the default qemu supports virtiofsd already (plus some cleanups)
kata-containers/kata-containers pull request #1434
Opened 2021-02-18 11:26 UTC by fidencio

This series is based atop of #1423, but I still don't feel comfortable to close that one in favour of this one here.

Fixes: #1424

2021-02-19 17:57 UTC, fidencio commented
@egernst, @wainersm, may I bother you for a review here?

2021-02-22 19:30 UTC, fidencio commented
/test

2021-02-22 20:20 UTC, fidencio commented
/test

2021-02-23 07:38 UTC, fidencio commented
/test-vfio

2021-02-23 13:15 UTC, pmores requested changes

2021-02-23 13:18 UTC, fidencio commented on docs/how-to/how-to-use-virtio-fs-with-kata.md
> +As of the 2.0 release of Kata Containers, [virtio-fs](https://virtio-fs.gitlab.io/) is the default filesystem sharing mechanism. While this does allow for workload compatibility, it does so with degr
I don't think it applies, but I think the sentence should be rewritten.  Let me do it and re-submit the series.
Thanks for the review, @pmores!

2021-02-23 13:26 UTC, fidencio commented on docs/how-to/how-to-use-virtio-fs-with-kata.md
> +As of the 2.0 release of Kata Containers, [virtio-fs](https://virtio-fs.gitlab.io/) is the default filesystem sharing mechanism. While this does allow for workload compatibility, it does so with degr
I ended up just removing that bit, as it seems the best to do for now.

We may need to re-write the document later on, but I'll leave that for later on.
I'm marking this conversation as resolved.

2021-02-23 13:26 UTC, fidencio commented
/test

2021-02-23 13:29 UTC, pmores approved these changes

2021-02-24 14:03 UTC, fidencio commented
/test-debian

2021-02-24 14:03 UTC, fidencio commented
/test-firecracker

2021-02-24 14:03 UTC, fidencio commented
/test-clh

2021-02-25 01:50 UTC, lifupan approved these changes

2021-02-25 01:50 UTC, merged