kata-deploy: add tolerations so it will install on a tainted master
kata-containers/kata-containers pull request #1742
Opened 2021-04-23 22:44 UTC by eadamsintel

If the master node is set to noSchedule then kata-deploy won't
install kata artifacts to the master node. If another pod
requests a kata runtimeclass and sets tolerations so that
it can/will schedule on master then the pod will fail. This
happened when a Kata webhook was installed into the cluster
and an nfd master pod tried to schedule on master, got mutated
to run kata, but failed to start. This patch will ensure
that the master node gets Kata artifacts installed to it
so that a pod could run if it requests a Kata runtime
and explicitely states it wants to run on master.

Fixes: #1741

Signed-off-by: Eric Adams <eric.adams@intel.com>

2021-04-24 01:42 UTC, cmaf commented
/test

2021-04-24 02:36 UTC, chavafg approved these changes

2021-04-24 02:38 UTC, chavafg commented
/cc @egernst @fidencio @bergwolf ptal
We would like to have this one in before doing release on Monday. 
Thanks

2021-04-24 13:02 UTC, egernst commented
I’m not sure if we should install on master.

2021-04-24 14:25 UTC, fidencio commented
> I’m not sure if we should install on master (by default).

I second that.

So, I see several issues combined together that led to this patch.
1. Shouldn't kubelet be aware of which nodes are capable of running that runtime class? Sending a workload of a runtime class to a node that doesn't support that sounds a whole lot as a bug in an upper layer.
2. kata-deploy shouldn't, by default, be mutating any of the control planes "base" workloads.  IMHO, those should still be running using the "default" container runtime.

I'd rather see those reported / fixed, but that's something we can discuss in the AC meeting on Tuesday.

2021-04-24 16:36 UTC, egernst commented
The runtimeclass definition includes nodeSelector and toleration definitions for this scenario. Normally you’d want to label nodes which have kata configured, and align the runtimeclass to this label setup. This should be out of scope of kata deploy itself, IMO. 

Either way, I think it’s up to the user to modify the example behavior to match their needs.

2021-04-24 16:37 UTC, eadamsintel commented
> > I’m not sure if we should install on master (by default).
> 
> I second that.
> 
> So, I see ~several~ a few issues combined together that led to this patch.
> 
> 1. Shouldn't kubelet be aware of which nodes are capable of running that runtime class? Sending a workload of a runtime class to a node that doesn't support that sounds a whole lot as a bug in an upper layer.
> 2. kata-webhook shouldn't, by default, be mutating any of the control planes "base" workloads.  IMHO, those should still be running using the "default" container runtime.
> 
> I'd rather see those reported / fixed, but that's something we can discuss in the AC meeting on Tuesday.

The issue for me came up because some pods like nfd have masters and workers that use tolerations to ensure the nfd master pod schedules on the kubernetes master ignoring the master tolerations. However, I had the Kata webhook running and it mutated the pod spec to make it a kata container because it can run as a kata container. I ended up in a state where pods failed to start because the kata artifacts were not actually installed on the system.  This wasn't a pod in the `kube-system` namespace but rather had a `node-feature-discovery` namespace.  The specific pod yaml I was using is https://github.com/onap/multicloud-k8s/blob/master/kud/deployment_infra/images/nfd-master.yaml.   I didn't test this scenario but what if the nfd master pod crashed for some reason and was automatically restarted?  If a webhook is running would it automatically try to make it run as kata forcing it to fail to restart?  Regardless if the webhook is running and you try to start the deployment then it will mutate to run kata.

Probably a cleaner solution to this would be that the runtimeclass can be limited to certain nodes as you suggested in 1.  I don't think it does that or at least what I observed on 1.18.9.

What concern do you have about kata-deploy running on a tainted master and installing the artifacts? For a pod to schedule with Kata on the master its pod spec would have to have those tolerations specifically added and kata would have to be added as a runtime class.

2021-04-24 16:42 UTC, egernst commented
NodeSelector in runtimeclass is what you want to prevent pods from scheduling on non-kata nodes. 

If most ppl don’t need/want kata on a control plane node, I’d rather it be an exception you make rather than a default.

2021-04-24 16:42 UTC, fidencio commented
> The runtimeclass definition includes nodeSelector and toleration definitions for this scenario. Normally you’d want to label nodes which have kata configured, and align the runtimeclass to this label setup. This should be out of scope of kata deploy itself, IMO.

Out of the scope of kata-deploy, indeed, but we should be coherent with the example we provide, for instance ...
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml we don't restrict the installation to a specific set of nodes, thus I'd expect to get the runtimeclass installed to all nodes regardless of those are tainted or not.

Does this sound reasonable?

> 
> Either way, I think it’s up to the user to modify the example behavior to match their needs.

Yep, but we must provide a solid working example.

2021-04-24 16:47 UTC, fidencio commented
> > > I’m not sure if we should install on master (by default).
> > 
> > 
> > I second that.
> > So, I see ~several~ a few issues combined together that led to this patch.
> > 
> > 1. Shouldn't kubelet be aware of which nodes are capable of running that runtime class? Sending a workload of a runtime class to a node that doesn't support that sounds a whole lot as a bug in an upper layer.
> > 2. kata-webhook shouldn't, by default, be mutating any of the control planes "base" workloads.  IMHO, those should still be running using the "default" container runtime.
> > 
> > I'd rather see those reported / fixed, but that's something we can discuss in the AC meeting on Tuesday.
> 
> The issue for me came up because some pods like nfd have masters and workers that use tolerations to ensure the nfd master pod schedules on the kubernetes master ignoring the master tolerations. However, I had the Kata webhook running and it mutated the pod spec to make it a kata container because it can run as a kata container. I ended up in a state where pods failed to start because the kata artifacts were not actually installed on the system. This wasn't a pod in the `kube-system` namespace but rather had a `node-feature-discovery` namespace. The specific pod yaml I was using is https://github.com/onap/multicloud-k8s/blob/master/kud/deployment_infra/images/nfd-master.yaml. I didn't test this scenario but what if the nfd master pod crashed for some reason and was automatically restarted? If a webhook is running would it automatically try to make it run as kata forcing it to fail to restart? Regardless if the webhook is running and you try to start the deployment then it will mutate to run kata.
> 
> Probably a cleaner solution to this would be that the runtimeclass can be limited to certain nodes as you suggested in 1. I don't think it does that or at least what I observed on 1.18.9.

That's something we do on the operator side.

> 
> What concern do you have about kata-deploy running on a tainted master and installing the artifacts? For a pod to schedule with Kata on the master its pod spec would have to have those tolerations specifically added and kata would have to be added as a runtime class.

Eric, to be honest, I mixed a few things in my mind and now I'm taking a step back.  I don't see any problem on installing the artifacts / runtime class if we don't limit that, and that makes me think we should have tolerations for any node (master or worker).

To be completely fair, I just think we should be coherent with the example we put out there for people to use, and that's it.  If we don't restrict nodes, we install in all, even the tainted ones.

Does this sound reasonable?

2021-04-24 16:47 UTC, eadamsintel commented
> NodeSelector in runtimeclass is what you want to prevent pods from scheduling on non-kata nodes.

Would I then need to update the runtimeclass yaml's so that they don't install the kata runtime class on the master?  I'm trying to figure out where the best place is to fix my issue.  I didn't see any runtime class examples using nodeselector so I wasn't exactly sure how to use it.

2021-04-24 16:51 UTC, eadamsintel commented
> To be completely fair, I just think we should be coherent with the example we put out there for people to use, and that's it. If we don't restrict nodes, we install in all, even the tainted ones.
> 
> Does this sound reasonable?

Yes it sounds reasonable. There are multiple ways I can solve the specific issue I have. I could just sed in place the kata-deploy.yaml before I apply to my cluster to add the same tolerations I put in this patch.  I am open to the best way to do this that is clean, consistent, and understandable by the community.  I didn't know that the runtime class could be restricted to specific nodes so that is perhaps a different way to solve this.  If you want I can come to the Tuesday meeting and we can discuss with everyone the cleanest example.

2021-04-24 16:57 UTC, egernst commented
> > NodeSelector in runtimeclass is what you want to prevent pods from scheduling on non-kata nodes.
> 
> Would I then need to update the runtimeclass yaml's so that they don't install the kata runtime class on the master? I'm trying to figure out where the best place is to fix my issue. I didn't see any runtime class examples using nodeselector so I wasn't exactly sure how to use it.

I’ll send an example later on.

2021-04-24 16:59 UTC, fidencio commented
> > To be completely fair, I just think we should be coherent with the example we put out there for people to use, and that's it. If we don't restrict nodes, we install in all, even the tainted ones.
> > Does this sound reasonable?
> 
> Yes it sounds reasonable. There are multiple ways I can solve the specific issue I have. I could just sed in place the kata-deploy.yaml before I apply to my cluster to add the same tolerations I put in this patch. I am open to the best way to do this that is clean, consistent, and understandable by the community. I didn't know that the runtime class could be restricted to specific nodes so that is perhaps a different way to solve this. If you want I can come to the Tuesday meeting and we can discuss with everyone the cleanest example.

My suggestion would be to keep the idea of your patch, but extending it to worker nodes also.
I'd wait for @egernst suggestion and I can have it merged before we do the next release.

The next release, by the way, will happen most likely on Wednesday, so we have time to discuss it here or even add it as a topic to the AC meeting next Tuesday.

2021-04-24 17:02 UTC, fidencio commented
About an example https://github.com/openshift/sandboxed-containers-operator/blob/master/deploy/deploy.yaml#L519

2021-04-24 17:20 UTC, eadamsintel commented
> My suggestion would be to keep the idea of your patch, but extending it to worker nodes also.
> I'd wait for @egernst opinion and I can have it merged before we do the next release.

Thanks and sounds good.  I saw your nodeSelector example but can that same line can be added to a runtimeclass yaml?  I think if you can limit the runtimeclass to worker nodes and untainted masters and the webhook is smart enough to see that a kata capable pod scheduled to run on a tainted master won't schedule one there than that would work great. 

I looked at your example @fidencio and some others on the nodeSelector.  Would it look something like the following?  I couldn't find any RuntimeClass nodeselector yaml examples but the [OpenShift documentation](https://docs.openshift.com/container-platform/4.5/rest_api/node_apis/runtimeclass-node-k8s-io-v1beta1.html) was very nice :). If this is how nodeSelector can work on just the Runtimeclass then this would be a logically consistent way to fix the discrepancy where a tainted master has a runtimeclass of Kata but no Kata artifacts installed on that node.  My example below would need to be updated for single node setups with untainted masters, but is this how it is done?

```
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata-qemu-virtiofs
handler: kata-qemu-virtiofs
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
nodeSelector:
    on-master: "false"
```

2021-04-24 17:26 UTC, egernst commented
Eric, I'd suggest updating the runtimeclass to make use of a nodeSelect, and utilize the label we are putting onto the nodes via the kata-deploy install script. 

I think adding the nodeSelect would be a great addition to make upstream, and this should solve your issue.

I feel strongly that we shouldn't be adding any tolerations to the kata-deploy DaemonSet.

```yaml
---
apiVersion: node.k8s.io/v1beta1
handler: kata-qemu
kind: RuntimeClass
overhead:
  podFixed:
    cpu: 350m
    memory: 2Gi
scheduling:
  nodeSelector:
    microvm: "true"
    katacontainers.io/kata-runtime: "true"
```

2021-04-24 17:27 UTC, fidencio commented
[...]
[...]
> I looked at your example @fidencio and some others on the nodeSelector. Would it look something like the following? I couldn't find any RuntimeClass nodeselector yaml examples but the [OpenShift documentation](https://docs.openshift.com/container-platform/4.5/rest_api/node_apis/runtimeclass-node-k8s-io-v1beta1.html) was very nice :). If this is how nodeSelector can work on just the Runtimeclass then this would be a logically consistent way to fix the discrepancy where a tainted master has a runtimeclass of Kata but no Kata artifacts installed on that node. My example below would need to be updated for single node setups with untainted masters, but is this how it is done?
> 
> ```
> ---
> kind: RuntimeClass
> apiVersion: node.k8s.io/v1beta1
> metadata:
>     name: kata-qemu-virtiofs
> handler: kata-qemu-virtiofs
> overhead:
>     podFixed:
>         memory: "160Mi"
>         cpu: "250m"
> nodeSelector:
>     on-master: "false"
> ```

Hmm. Taking a quick look at https://kubernetes.io/docs/concepts/containers/runtime-class/#scheduling I don't think that would do.

I can try to dig into an example / what we do with the Operator later on, or on Monday, unless @egernst or @jensfr beat me on that.

2021-04-24 17:35 UTC, egernst requested changes
We should not by default run this daemonset on master nodes. it sounds like your issue is really that Kata was trying to be used on a node that didn't have Kata installed on it. That's what the nodeSelector as part of runtimeclass is used for. Let's instead update the example kata-runtimeclasses we provide.

2021-04-24 17:43 UTC, egernst commented
A more fundamental question: Do you actually want node feature discovery to run within a kata pod? Something at that level makes more sense to be running bare-metal or within a runc based container.

2021-04-24 19:38 UTC, eadamsintel commented
> A more fundamental question: Do you actually want node feature discovery to run within a kata pod? Something at that level makes more sense to be running bare-metal or within a runc based container, so it can gather information from the node, rather than from the guest-VM?

Maybe I don't. I need to talk to the project owner how they want to handle this. It passed the test when using nfd as a kata pod, but I didn't look in detail to see if it was correctly exposing items.  The nfd pods were not the only ones that this happened on.  The project I am trying to integrate Kata into prefers to pull from upstream yamls vs keeping local copies but the project is still in the relatively early days. Things can change. 

Still though if the Runtimeclass example can be setup to not allow scheduling on a tainted master node then I think would be a better way to handle this  I've only used nodeselector in its most basic form in the past so I am not sure if you can set it up to not install on node with taints of noschedule.

2021-04-24 20:28 UTC, jensfr commented
> > ---
> > kind: RuntimeClass
> > apiVersion: node.k8s.io/v1beta1
> > metadata:
> >     name: kata-qemu-virtiofs
> > handler: kata-qemu-virtiofs
> > overhead:
> >     podFixed:
> >         memory: "160Mi"
> >         cpu: "250m"
> > nodeSelector:
> >     on-master: "false"
> > ```
> 
> Hmm. Taking a quick look at https://kubernetes.io/docs/concepts/containers/runtime-class/#scheduling I don't think that would do.
> 
> I can try to dig into an example / what we do with the Operator later on, or on Monday, unless @egernst or @jensfr beat me on that.

See this https://github.com/openshift/sandboxed-containers-operator/blob/2b224191eb620e4e9a38506b7ba454e581b5bc2d/controllers/openshift_controller.go#L281 for an example in our operator. By default we set it to match nodes with label "node-role.kubernetes.io/worker" unless another label is specified by the user to select a different subset of nodes.

2021-04-26 09:42 UTC, fidencio commented
> We should not by default run this daemonset on master nodes.

Why?  I back you up when we're doing a k8s / OpenShift deployment, and I see that running the daemonset on master nodes, mainly with combined with the kata-webhook may become very problematic.  However, and sorry for playing the devil's advocate here, I think a huge amount of the people "trying" kata-containers will end up trying the project on a single node k8s cluster, either virtualised (via minikube or any other similar solution) or BM, but still a single node k8s cluster.

2021-04-26 15:57 UTC, egernst commented
@fidencio - in that single node cluster setup, the user (or setup scripts) will remove the taint on the master node, and based on that the kata-deploy daemonset (and all other daemonsets) would run on that node.  My main point is we should not add a. toleration for the master node taint.

2021-04-26 20:18 UTC, eadamsintel commented
> Eric, I'd suggest updating the runtimeclass to make use of a nodeSelect, and utilize the label we are putting onto the nodes via the kata-deploy install script.

I did a test with adding `nodeSelector` to the `RuntimeClass` and it seemed to work more logically even with the webhook installed. If I have the webhook running and start a pod that I tell to run on master then the pod will get stuck in pending with "0/2 nodes are available: 2 node(s) didn't match node selector."  This is more logically consistent with how things would work and is better than the error about missing artifacts. 

The only way you would ever get into this scenario is if you intentionally or through the webhook specified to run Kata and also specified this workload has to run on master regardless of its taint. Still though, if you did install Kata artifacts on every node including master then pods in this scenario would still run and not be stuck in pending. I added this as an agenda item for tomorrow's call to get the rest of the communities feedback. 

I agree that nfd is probably not something we want to run with Kata anyways, but I think it is worth exploring to see if there are other use cases that make sense. As it is right now the default behavior is that you can't run isolated container workloads on a master.

2021-04-30 17:01 UTC, eadamsintel commented
> okay to close this PR?

It is ok by me but @fidencio mentioned he wanted to keep it open during the Tuesday call to link to it for some future webhook updates so that the webhook is more intelligent with its allow/donotallow list.

2021-05-03 23:52 UTC, egernst commented
I'll close the PR, but keep the relevant issue open for him to reference.

Thanks @eadamsintel

2021-05-03 23:52 UTC, closed without merging