runtime: Fix field alignment on s390x
kata-containers/kata-containers pull request #2774
Opened 2021-09-30 10:59 UTC by Jakob-Naucke

Follow-up of #2237 for s390x -- field alignment isn't always minimal

Depends-on: github.com/kata-containers/tests#4047
Fixes: #2773
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

2021-09-30 10:59 UTC, Jakob-Naucke commented
let's see /test-s390x

2021-09-30 13:44 UTC, Jakob-Naucke commented
dependency PR was invalid -- /test-s390x

2021-10-01 22:39 UTC, Jakob-Naucke commented
okay, https://github.com/kata-containers/tests/pull/4048 is in. /test-s390x

2021-10-03 15:42 UTC, snir911 commented
/test-s390x

2021-10-04 16:31 UTC, cmaf submitted a review, later dismissed

2021-10-04 16:36 UTC, cmaf commented
@Jakob-Naucke this is in the s390x output: 
```
[static-checks.sh:360] INFO: Running golangci-lint on /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers
++ cd /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers
++ GO111MODULE=auto
++ eval golangci-lint 'run -c /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/tests/.ci/.golangci.yml' .
+++ golangci-lint run -c /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/tests/.ci/.golangci.yml .
qemu_arch_base.go:186:2: `protection` is unused (structcheck)
	protection           guestProtection
	^
```

2021-10-05 09:36 UTC, Jakob-Naucke commented
Adding a `nolint` for that one -- I cannot reproduce this on x86 for whatever reason. Invalidating review due to a new commit. /test-s390x

2021-10-05 09:41 UTC, Jakob-Naucke commented
needed a `gofmt`, /test-s390x

2021-10-05 10:17 UTC, Amulyam24 commented
Hi @Jakob-Naucke , I have one last fix for static checks on ppc64le, would you mind if I add it in this PR?(since this aligns to !x86 fixes)

2021-10-05 10:23 UTC, Jakob-Naucke commented
@Amulyam24 fine with me. Please do add a comment in #2773 about the failure that your amendment will fix.

2021-10-05 11:14 UTC, Jakob-Naucke commented
/test

2021-10-05 11:22 UTC, Amulyam24 commented
Thanks @Jakob-Naucke :)

2021-10-05 13:57 UTC, Jakob-Naucke commented
ARM failure is tracked in #2789. FC failure is tracked in #3998. /retest-fc

2021-10-05 14:12 UTC, Jakob-Naucke commented
looks like one-off /retest-fc

2021-10-05 14:30 UTC, jongwu commented
Hello @Jakob-Naucke -, how about picking up my commits [here](https://github.com/kata-containers/kata-containers/pull/2790/commits) in this PR to speed up review.

2021-10-05 14:48 UTC, Jakob-Naucke commented
you get a merge, you get a merge, everyone gets a merge!!! /test

2021-10-05 16:42 UTC, Jakob-Naucke commented
closing and reopening due to GHA not running

2021-10-05 16:43 UTC, Jakob-Naucke commented
/test

2021-10-06 11:01 UTC, fidencio requested changes
I've made the same comments I made on #2790.

Once those are addressed we can have this one merged.
Thanks both @Jakob-Naucke and @jongwu!

2021-10-06 11:15 UTC, jongwu commented
thanks @fidencio. 
hello @Jakob-Naucke -, can you help resolve these change requests, as the [PR](https://github.com/kata-containers/kata-containers/pull/2790) is closed. I think it's easy for you.

2021-10-06 13:20 UTC, jongwu commented
Hello @Jakob-Naucke -, I have pushed the changes to my check branch [here](https://github.com/jongwu/kata-containers/tree/check). You can pick it up, thanks!

2021-10-06 13:48 UTC, Jakob-Naucke commented
I took the freedom to apply @fidencio's suggestion. /test

2021-10-06 17:20 UTC, Jakob-Naucke commented on src/runtime/virtcontainers/qemu_arch_base.go
> +	tdxProtection //nolint
more funnily, it also did not fail on s390x (and ppc64le apparently), see [my comment above](https://github.com/kata-containers/kata-containers/pull/2774#issuecomment-936092091)

2021-10-06 17:25 UTC, amshinde commented on src/runtime/virtcontainers/qemu_arch_base.go
> +	tdxProtection //nolint
@Jakob-Naucke thanks for the confirmation. Yes, I am not sure what the lint check is failing on arm at this point.
I am not sold out on the nolint solution, however if this is blocking a lot of PRs, I am fine with opening an issue and addressing this properly in a future PR.

2021-10-06 17:30 UTC, Jakob-Naucke commented on src/runtime/virtcontainers/qemu_arch_base.go
> +	tdxProtection //nolint
@amshinde okay, let's do it that way -- #2801

2021-10-06 17:56 UTC, amshinde approved these changes

2021-10-06 17:57 UTC, merged