osbuilder/scripts: fix yq 2.x failed to get rust version in yaml
kata-containers/kata-containers pull request #2827
Opened 2021-10-13 02:01 UTC by Kvasscn

yq 2.x version not support -X flag in read command, so remove it.

Fixes: #2824

Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

2021-11-09 12:17 UTC, Jakob-Naucke requested changes
@Kvasscn DYT this needs a backport? Also, as we are using this functionality, I think the answer is not to remove that flag, but to not allow <3 (nvm it would be best to move to v4 syntax in general).

2021-11-09 12:17 UTC, Jakob-Naucke commented on tools/osbuilder/scripts/lib.sh
> +    yq_version=$($yq -V 2>&1)
I agree.

2021-11-15 11:09 UTC, fidencio commented
> @Kvasscn DYT this needs a backport? Also, as we are using this functionality, I think the answer is not to remove that flag, but to not allow <3 (nvm it would be best to move to v4 syntax in general).

Yep, we'd be better just moving to v4 syntax as soon as possible.

2021-12-23 12:10 UTC, jodh-intel commented
Any update on this?

2022-01-26 12:41 UTC, fidencio commented
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

2022-02-01 09:21 UTC, fidencio commented
As this PR has been waiting for an update since October 2021, I'm closing it for now.

@Kvasscn, please, if you find some free cycles to work on this PR, please, just re-open it and let us know.
Thanks for the contribution and looking forward to seeing an up-to-date version of this PR.

2022-02-01 09:21 UTC, closed without merging