virtcontainers: clh: Use virtio-console `Null` mode by default
kata-containers/kata-containers pull request #2937
Opened 2021-10-29 19:16 UTC by likebreath

We observed that the guest Linux kernel picks its own default console,
e.g. `ttyS0` (the serial console), when we don't specify the console
parameter expicitly. For this reason, the guest kernel will try to read
and write to the serial port that is not emulated by the VMM. It brings
several unnecessary PIO/ VMM exits that slow-down the boot time. Also,
we don't have control over the guest that may read/write to the console
that can further introduce more PIO and slow-down the container. As a
trade-off, using the virtio-console `Null` mode along with setting the
guest kernel console explicitly as `hvc0` is the best way for steady
performance.

Fixes: #2936

Signed-off-by: Bo Chen <chen.bo@intel.com>

2021-10-29 19:17 UTC, likebreath commented
/test

2021-10-29 19:49 UTC, devimc approved these changes

2021-11-01 10:44 UTC, jodh-intel requested changes
Hi @likebreath - this fails if you enable hypervisor debug:

```
ctr: failed to create shim: error: 500  reason: VmBoot(VmBoot(ConfigValidation(DoubleTtyMode))): unknown
```

There is some more detail about that on https://github.com/kata-containers/kata-containers/pull/2751.

2021-11-10 18:42 UTC, closed without merging

2021-11-10 18:42 UTC, likebreath commented
See comment: https://github.com/kata-containers/kata-containers/issues/2936#issuecomment-965633218