update apiVersion
kata-containers/kata-containers pull request #3188
Opened 2021-12-03 08:40 UTC by weiyuanke

2021-12-03 10:58 UTC, liubin approved these changes

2021-12-03 11:05 UTC, lifupan approved these changes

2021-12-03 12:59 UTC, fidencio commented
Wait, wait, let's take a step back here.
Would this work without issues a kubernetes v1.20 cluster?  I **think** it will not, but I may be totally wrong here.

IMHO, we should only do the switched after ensuring the oldest supported k8s can support "node.k8s.io/v1".  If that's the case, then "yay!", let's go ahead and merge this.  Otherwise I'd be slightly more careful about those changes and do then later in the cycle.

2021-12-03 13:18 UTC, fidencio requested changes
In general LGTM.  Please, just follow the comments made inline and we can have it merged.

I also checked that RuntimeClass became stable on 1.20 release, so the change is good to go.

2021-12-03 13:18 UTC, fidencio commented on docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
> +First, follow the [How to use Kata Containers and Containerd](containerd-kata.md) to install and configure containerd.
This change is not related to the problem you're fixing, please, drop it.

2021-12-03 13:18 UTC, fidencio commented on docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
> +  [Service]
This change is not related to the problem you're fixing, please, drop it as well.

2021-12-03 13:18 UTC, fidencio commented on docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
> +
Same here about the additional line.  Please, drop it.

2021-12-08 08:35 UTC, liubin commented
/test

2021-12-13 05:18 UTC, weiyuanke commented
@fidencio PTAL

2021-12-21 08:33 UTC, liubin commented
@fidencio Can you take a look again?

2021-12-23 12:25 UTC, jodh-intel approved these changes
Thanks @weiyuanke.

lgtm

@fidencio - ptal.

2022-01-10 11:38 UTC, jodh-intel commented
Ping @fidencio.

2022-01-17 22:19 UTC, fidencio commented
Folks, please, feel free to send me a message on Slack about those PRs that get blocked and end up lost on my email.
Huge sorry from my side, let me take a look at it now.

2022-01-17 22:19 UTC, fidencio approved these changes
lgtm, thanks @weiyuanke!

2022-01-17 22:20 UTC, merged