kata-runtime enable hugepage support
kata-containers/kata-containers pull request #3696
Opened 2022-02-17 03:18 UTC by shippomx

fix the issue I have mentioned in #3695 kata-runtime doesn't pass the hugepages params to kata-agent.

2022-02-17 09:42 UTC, jodh-intel commented
Thanks for raising @shippomx.

@liubin - I think we'd better get your input on this.

2022-02-17 09:56 UTC, liubin commented
/test

2022-02-17 09:58 UTC, liubin commented
I'm not sure passing the resource limit of huge pages to the container is required, the huge pages mounted with the size option.

/cc @lifupan

2022-02-18 02:46 UTC, shippomx commented
@liubin Is there no need to limit container resourses in guest OS? I am confused.

2022-02-23 08:17 UTC, Marshalzxy commented
> I'm not sure passing the resource limit of huge pages to the container is required, the huge pages mounted with the size option.
> 
> /cc @lifupan
In my opinion, container should be limit by huge page limition. Huge page limit is defined in OCI runtime-spec config-linux https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md, Kata should realize it.

2022-02-23 17:02 UTC, fengwang666 commented
@shippomx Can you fix the commit message and static check error?

2022-02-24 02:08 UTC, shippomx commented
The commit message have been amended @fengwang666

2022-02-28 16:07 UTC, Jakob-Naucke commented
@liubin @lifupan any further takes on this?
Meanwhile @shippomx can you fix the indentation in your commit message and format it with a [subsystem](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#subsystem)? I also think the commit subject could be a bit more descriptive ("enabling hugepage support" is a better description for something like #3344 I guess)

2022-03-01 01:16 UTC, shippomx commented
> 
I do this commit at the first time. At least 2 approving reviews are required by reviewers with write access, the ci sequences will be triggered. And the [https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#subsystem] errors that I have never seen in this commit.

2022-03-01 10:58 UTC, Jakob-Naucke commented
@shippomx your commit would have to be formatted something like:
```
runtime: Pass the hugepages resources to agent

The hugepages resources claimed by containers should be limited
by cgroup in the guest OS.

<fixes/signoff>
```

2022-03-01 15:23 UTC, liubin commented
hi @shippomx there are two issues with your commit message, you can see [here](https://github.com/kata-containers/kata-containers/runs/5377392690?check_suite_focus=true)

One is about the DCO:

```
Expected "miao.xia <xia.miao1@zte.com.cn>", but got "shippomx <flysommer@outlook.com>".

  What should I do to fix it ?

  All proposed commits should include a Signed-Off-By: <your-email-address> line in their commit message.
  This is most conveniently done by using --signoff (-s) when running git commit.
```

You can check your `git config user.email` and `user.name` and which is used in `Signed-off-By`.

Another is about the message body, you should follow the rule that @Jakob-Naucke gives. Here is a [Chinese version](http://liubin.org/kata-dev-book/src/kata-dev-env-setup.html#kata-containers-%E5%BC%80%E5%8F%91%E6%B5%81%E7%A8%8B) about it.

2022-03-09 03:34 UTC, shippomx commented
@liubin @Jakob-Naucke Can you help me review this commit?

2022-03-09 03:39 UTC, liubin commented
/test

2022-03-09 03:40 UTC, liubin commented
@shippomx Here is a commit message check error:

```
Error: 

  1d88ce8313061beed89acacade7f4e52de070466    Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

2022-03-10 12:18 UTC, gkurz requested changes
Hi @shippomx !

There are still issues with the commit message:
- as suggested several times in the conversation, the appropriate title for this change should be `runtime/virtcontainers: Pass the hugepages resources to agent`
     => please drop the `virtcontainers: enabling hugepage support` line.
- the origin of the change is unclear : it appears to be authored by `miao.xia <xia.miao1@zte.com.cn>` but the PR comes from you `shippomx <flysommer@outlook.com>`.
     => you must add your Signed-off-by: tag to validate the DCO
- the preferred format of the Signed-off-by: tag is "Full Name <some.email@address>"

e.g. something like this:

```
runtime/virtcontainers: Pass the hugepages resources to agent

The hugepages resources claimed by containers should be limited
by cgroup in the guest OS.

Fixes: https://github.com/kata-containers/kata-containers/issues/3695
Signed-off-by: Miao Xia <xia.miao1@zte.com.cn>
Signed-off-by: Shippom XXXX <flysommer@outlook.com>
```

2022-03-11 09:37 UTC, gkurz requested changes
Hi @shippomx !

I see that you updated your GH profile, so we just need one Signed-off-by tag since you are the author of the change. I'll just ask one more change and we should be good, please make it:
```
Signed-off-by: Miao Xia <xia.miao1@zte.com.cn>
```

2022-03-15 02:54 UTC, shippomx commented
@gkurz thinks, the user name confused me a lot.

2022-03-15 09:08 UTC, gkurz commented
> @gkurz thinks, the user name confused me a lot.

We are very close. Consider the output of the [Commit Message Check](https://github.com/kata-containers/kata-containers/runs/5547471053?check_suite_focus=true#step:3:12) :

```
0dae697a30aa4f0803406bd8b32b9f85f85debf7    Expected "miao.xia <xia.miao1@zte.com.cn>", but got "Miao Xia <xia.miao1@zte.com.cn>".
```

"miao.xia <xia.miao1@zte.com.cn>" is basically the From: line of the patch as seen in the [raw version](https://github.com/kata-containers/kata-containers/commit/0dae697a30aa4f0803406bd8b32b9f85f85debf7.patch) :

```
From: "miao.xia" <xia.miao1@zte.com.cn>
```

The email address is ok but the name is not. You should fix that in your local repository before pushing the commit to GH. Ensure your name is correctly set for future commits :

```
git config --global user.name "Miao Xia"
```

This won't change existing commits in your local repo but you should be able to fix the last one with:

```
git commit --amend --author="Miao Xia <xia.miao1@zte.com.cn>"
```

I hope that helps.

2022-03-15 09:37 UTC, shippomx commented
@gkurz I have followed your warmly steps. :flushed:

2022-03-15 09:46 UTC, liubin commented
For now, the check may accept two formats:

```
Fixes: #3695
```

or

```
Fixes: github.com/kata-containers/kata-containers#3695
```

2022-03-15 10:48 UTC, shippomx commented
@liubin ok thanks.

2022-03-15 11:22 UTC, gkurz commented
> For now, the check may accept two formats for `Fixes`:
> 
> ```
> Fixes: #3695
> ```
> 
> or
> 
> ```
> Fixes: github.com/kata-containers/kata-containers#3695
> ```

Yes and the second form isn't especially used, nor useful. I've created issue #3897 to propose that the check accepts plain GH URLs instead, e.g.

```
 Fixes: https://github.com/kata-containers/kata-containers/issues/3695
```

2022-03-15 11:23 UTC, gkurz approved these changes
Commit message is ok now. Thanks Miao Xia !

2022-03-17 01:53 UTC, shippomx commented
@liubin Can you take some little time to review this PR?

2022-03-19 03:57 UTC, fengwang666 approved these changes

2022-03-19 03:57 UTC, fengwang666 commented
/test

2022-03-25 09:23 UTC, jodh-intel approved these changes
Thanks @shippomx.

lgtm

/cc @liubin.

2022-04-02 08:18 UTC, shippomx commented
How to retrigger this check? Just jenkins-ci-ARM-ubuntu-18-04 did not pass.

2022-04-03 16:59 UTC, gkurz commented
/retest-arm

2022-04-06 13:06 UTC, gkurz commented
/retest-arm

2022-04-06 14:47 UTC, merged