tools: release: Do not consider release candidates as stable releases
kata-containers/kata-containers pull request #3848
Opened 2022-03-07 17:55 UTC by fidencio

During the release of 2.4.0-rc0 @egernst noticed an incositency in the
way we handle release tags, as release candidates are being taken as
"stable" releases, while both the kata-deploy tests and the release
action consider this as "latest".

Ideally we should have our own tag for "release candidate", but that's
something that could and should be discussed more extensively outside of
the scope of this quick fix.

For now, let's align the code generating the PR for bumping the release
with what we already do as part of the release action and kata-deploy
test, and tag "-rc"  as latest, regardless of which branch it's coming
from.

Fixes: #3847

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

2022-03-07 19:56 UTC, fidencio commented
/test

2022-03-07 21:12 UTC, fidencio commented
/retest-ubuntu-metrics

2022-03-07 21:59 UTC, egernst approved these changes

2022-03-07 22:00 UTC, egernst requested changes

2022-03-07 22:00 UTC, egernst commented on tools/packaging/release/update-repository-version.sh
> +			## this covers case 3), as it has changes on kata-deploy / kata-cleanup  files
the sed below needs fixing?

2022-03-07 22:01 UTC, fidencio commented on tools/packaging/release/update-repository-version.sh
> +			## this covers case 3), as it has changes on kata-deploy / kata-cleanup  files
Fixed!

2022-03-07 22:02 UTC, fidencio commented
/test

2022-03-08 09:39 UTC, jodh-intel approved these changes
Thanks @fidencio.

lgtm

2022-03-08 13:56 UTC, fidencio commented
/retest-vfio

2022-03-08 23:08 UTC, egernst approved these changes

2022-03-08 23:09 UTC, merged