runtime: Allow and require no initrd for SE
kata-containers/kata-containers pull request #3923
Opened 2022-03-21 11:20 UTC by Jakob-Naucke

Previously, it was not permitted to have neither an initrd nor an image.
However, this is the exact config to use for Secure Execution, where the
initrd is part of the image to be specified as `-kernel`. Require the
configuration of no initrd for Secure Execution.

Also
- remove redundant code for image/initrd checking -- no need to check in
  `newQemuHypervisorConfig` (calling) when it is also checked in
  `getInitrdAndImage` (called)
- use `QemuCCWVirtio` constant when possible

Fixes: #3922

and an extra fix

2022-03-21 12:29 UTC, Jakob-Naucke commented
Rebased upon `main` following suggestion from @fidencio. Removing osbuilder fix that doesn't really belong here.

2022-03-21 12:38 UTC, fidencio approved these changes
lgtm, thanks @Jakob-Naucke!

2022-03-23 18:04 UTC, cmaf approved these changes
thanks @Jakob-Naucke

2022-03-23 18:06 UTC, cmaf commented
/test

2022-03-24 10:37 UTC, Jakob-Naucke commented
Plain rebase to re-trigger stalled check

2022-03-24 10:37 UTC, Jakob-Naucke commented
/test

2022-03-25 09:36 UTC, jodh-intel requested changes
Hi @Jakob-Naucke - please can you update the unit test code for this change (`src/runtime/virtcontainers/hypervisor_test.go`).

2022-03-25 17:36 UTC, Jakob-Naucke commented
thanks @jodh-intel /test

2022-03-28 10:22 UTC, Jakob-Naucke commented
for the sake of it /test-s390x

2022-04-04 08:32 UTC, amshinde approved these changes

2022-04-05 07:24 UTC, jodh-intel approved these changes
Thanks @Jakob-Naucke.

lgtm

2022-04-05 07:26 UTC, merged

2022-05-13 16:36 UTC, egernst commented on src/runtime/virtcontainers/hypervisor.go
> +	} else if conf.BlockDeviceDriver == config.VirtioBlock && conf.HypervisorMachineType == QemuCCWVirtio {
Late to the party here but we should ensure that QEMU (or any VMM really) specific code is contained within the VMM implementation itself, and doesn't leak into the (agnostic) hypervisor.go.

More specifically, not every HOST_OS supports QEMU - see https://github.com/Jakob-Naucke/kata-containers/blob/ff17c756d2cb777ce63af2c9aa5a3dd7dc5e2eba/src/runtime/virtcontainers/qemu.go#L1-L2

2022-05-13 16:38 UTC, egernst commented on src/runtime/virtcontainers/hypervisor.go
> +	} else if conf.BlockDeviceDriver == config.VirtioBlock && conf.HypervisorMachineType == QemuCCWVirtio {
Issue opened for addressing: 

https://github.com/kata-containers/kata-containers/issues/4251