kernel: add basename kernel symlinks when suffix is used
kata-containers/kata-containers pull request #5010
Opened 2022-08-25 23:07 UTC by ryansavino

'kata-runtime kata-env' throws an error when the kernel is built for a specific TEE like SEV.
Basename kernel symlinks added to prevent error.

Fixes: #5008

Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

2022-08-25 23:25 UTC, fidencio requested changes
No, that's not the way to go.

We rather fix `kata-runtime kata-env`, otherwise we'll be simply overwriting the link to the non-TEE kernel, which is a valid use case for when we ship, for instance, normal Kata Containers and CC Kata Containers as part of the same payload.

2022-08-25 23:27 UTC, fidencio commented
Also, this is what I see as part of the TDX CI:
```
01:10:15 [Kernel]
01:10:15   Path = "/usr/share/kata-containers/vmlinuz-SPR-BKC-PC-v9.6-96-tdx"
01:10:15   Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none tdx_disable_filter"
01:10:15 
```

What are you getting as part of the SEV CI?

2022-08-25 23:37 UTC, fidencio commented
> 

Just checked the issue.  The error you're facing should be fixed on the configuration that you're using so, there, you point to the vmlinux-sev.container (or similar ;-)).  That's what we do with TDX, and with any other kernel that's not the vanilla one.

2022-08-26 09:35 UTC, ryansavino commented
Thanks for the walkthrough @fidencio. I've created PR #5013 to address this. Closing this PR.

2022-08-26 09:35 UTC, closed without merging

2022-08-26 09:36 UTC, ryansavino commented
> Also, this is what I see as part of the TDX CI:
> 
> ```
> 01:10:15 [Kernel]
> 01:10:15   Path = "/usr/share/kata-containers/vmlinuz-SPR-BKC-PC-v9.6-96-tdx"
> 01:10:15   Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none tdx_disable_filter"
> 01:10:15 
> ```
> 
> What are you getting as part of the SEV CI?

I can give you an update on what the SEV CI flow shows once #5013 is merged.