packaging: Fix sev cache kernel issue
kata-containers/kata-containers pull request #6363
Opened 2023-02-23 17:35 UTC by UnmeshDeodhar

Fix cache kernel issue introduced by #6177

Fixes: #6362

2023-02-23 19:55 UTC, UnmeshDeodhar commented
/test

2023-02-23 20:36 UTC, fidencio commented
@UnmeshDeodhar, can I see the logs with the errors you're facing?

2023-02-23 20:38 UTC, UnmeshDeodhar commented
@fidencio Here is the log from the cache kernel job: http://jenkins.katacontainers.io/view/Cached%20jobs/job/kata-containers-2.0-kernel-sev-cc-x86_64-DEBUG/27/console

2023-02-23 20:45 UTC, fidencio commented
> @fidencio Here is the log from the cache kernel job: http://jenkins.katacontainers.io/view/Cached%20jobs/job/kata-containers-2.0-kernel-sev-cc-x86_64-DEBUG/27/console

```
18:05:26 quay.io/kata-containers/cc-builders:kernel-e8c63ccc4d93ae1e4019ed1e310938328e8044bb-x86_64
18:05:26 ./tools/packaging/static-build/cache_components.sh: line 50: kernel_version: unbound variable
18:05:26 Build step 'Execute shell' marked build as failure
```

2023-02-23 20:57 UTC, fidencio requested changes
Okay, now I got why you were setting up those, and I must admit I totally missed the `get_config_version` call.

Anyways, the correct fix is, instead of setting those var on every single place you call `get_config_version`, you make sure those are correct setup from within that function.

I think this is the correct fix:
````
⋊> kata-containers on CCv0 ≡ ⨯ git diff
diff --git a/tools/packaging/guest-image/build_image.sh b/tools/packaging/guest-image/build_image.sh
index ee77f396b..86c00dd46 100755
--- a/tools/packaging/guest-image/build_image.sh
+++ b/tools/packaging/guest-image/build_image.sh
@@ -20,7 +20,7 @@ source "${packaging_root_dir}/scripts/lib.sh"
 readonly osbuilder_dir="$(cd "${repo_root_dir}/tools/osbuilder" && pwd)"
 
 patches_path=""
-readonly default_patches_dir="${packaging_root_dir}/kernel/patches"
+readonly default_patches_dir="${repo_root_dir}/tools/packaging/kernel/patches"
 
 export GOPATH=${GOPATH:-${HOME}/go}
 
diff --git a/tools/packaging/scripts/lib.sh b/tools/packaging/scripts/lib.sh
index ef74acad3..de136312c 100755
--- a/tools/packaging/scripts/lib.sh
+++ b/tools/packaging/scripts/lib.sh
@@ -115,7 +115,7 @@ get_config_and_patches() {
 
 get_config_version() {
        get_config_and_patches
-       config_version_file="${default_patches_dir}/../kata_config_version"
+       config_version_file="${repo_root_dir}/tools/packaging/kernel/kata_config_version"
        if [ -f "${config_version_file}" ]; then
                cat "${config_version_file}"
        else
````

The changes related kernel_version -> current_kernel_version are good.

2023-02-23 20:57 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_component \
This change is not related to the PR.

2023-02-23 20:57 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +readonly default_patches_dir="${packaging_root_dir}/kernel/patches"
Imagine we're calling `get_config_version` in different files, and then we'd have to set this up in each one of the calls.

This makes me think that here is definitely not the place to add set this variables.

2023-02-23 20:57 UTC, fidencio commented on tools/packaging/static-build/cache_components.sh
> +readonly default_patches_dir="${packaging_root_dir}/kernel/patches"
Like adding this here again. :-)

2023-02-23 20:58 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_component \
My bad, it totally is. :-)

2023-02-24 05:31 UTC, fidencio approved these changes
lgtm, thanks @UnmeshDeodhar!

2023-02-24 05:31 UTC, fidencio commented
/test

2023-02-24 05:36 UTC, UnmeshDeodhar commented
/test

2023-02-24 16:17 UTC, GabyCT approved these changes

2023-02-24 22:15 UTC, UnmeshDeodhar commented
@GabyCT @fidencio fyi, all tests are passing except tdx. We except significant time gains with this PR.

2023-02-25 14:05 UTC, fidencio commented
/test-tdx

2023-02-27 08:59 UTC, fidencio commented
/test-tdx

2023-02-27 11:55 UTC, fidencio commented
http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/730/ passed but didn't report back, we can get this one merged.

2023-02-27 11:57 UTC, merged