CCv0: Merge main into CCv0 branch
kata-containers/kata-containers pull request #6506
Opened 2023-03-20 13:25 UTC by Megan-Wright

Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #6504
Signed-off-by: Megan Wright <megan.wright@ibm.com>

2023-03-20 13:30 UTC, Megan-Wright commented
```
 git diff --stat upstream/main -- . ':!*/vendor/*'
 .github/workflows/cc-payload-after-push-amd64.yaml                            |  159 ++
 .github/workflows/cc-payload-after-push-s390x.yaml                            |  153 ++
 .github/workflows/cc-payload-after-push.yaml                                  |   39 +
 .github/workflows/cc-payload-amd64.yaml                                       |  142 ++
 .github/workflows/cc-payload-s390x.yaml                                       |  134 ++
 .github/workflows/cc-payload.yaml                                             |   39 +
 .github/workflows/commit-message-check.yaml                                   |    4 +-
 .github/workflows/deploy-ccv0-demo.yaml                                       |  124 ++
 .github/workflows/kata-deploy-push.yaml                                       |    4 +
 .github/workflows/static-checks.yaml                                          |    4 +-
 ci/install_libseccomp.sh                                                      |    3 +-
 ci/lib.sh                                                                     |   83 +
 docs/how-to/README.md                                                         |    3 +
 docs/how-to/ccv0.sh                                                           |  640 ++++++
 docs/how-to/data/confidential-agent-config.toml.in                            |   45 +
 docs/how-to/how-to-build-and-test-ccv0.md                                     |  475 ++++
 ...rate-a-kata-containers-payload-for-the-confidential-containers-operator.md |   44 +
 docs/how-to/how-to-set-sandbox-config-kata.md                                 |   10 +
 docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md                      |    2 +
 docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md                           |    1 +
 docs/how-to/how-to-use-virtio-mem-with-kata.md                                |    2 +
 src/agent/Cargo.lock                                                          | 4077 ++++++++++++++++++++++++++++++-----
 src/agent/Cargo.toml                                                          |   14 +-
 src/agent/rustjail/src/cgroups/fs/mod.rs                                      |   19 +-
 src/agent/rustjail/src/lib.rs                                                 |    8 +-
 src/agent/src/config.rs                                                       |  220 +-
 src/agent/src/device.rs                                                       |   18 +-
 src/agent/src/image_rpc.rs                                                    |  337 +++
:...skipping...
 .github/workflows/cc-payload-after-push-amd64.yaml                            |  159 ++
 .github/workflows/cc-payload-after-push-s390x.yaml                            |  153 ++
 .github/workflows/cc-payload-after-push.yaml                                  |   39 +
 .github/workflows/cc-payload-amd64.yaml                                       |  142 ++
 .github/workflows/cc-payload-s390x.yaml                                       |  134 ++
 .github/workflows/cc-payload.yaml                                             |   39 +
 .github/workflows/commit-message-check.yaml                                   |    4 +-
 .github/workflows/deploy-ccv0-demo.yaml                                       |  124 ++
 .github/workflows/kata-deploy-push.yaml                                       |    4 +
 .github/workflows/static-checks.yaml                                          |    4 +-
 ci/install_libseccomp.sh                                                      |    3 +-
 ci/lib.sh                                                                     |   83 +
 docs/how-to/README.md                                                         |    3 +
 docs/how-to/ccv0.sh                                                           |  640 ++++++
 docs/how-to/data/confidential-agent-config.toml.in                            |   45 +
 docs/how-to/how-to-build-and-test-ccv0.md                                     |  475 ++++
 ...rate-a-kata-containers-payload-for-the-confidential-containers-operator.md |   44 +
 docs/how-to/how-to-set-sandbox-config-kata.md                                 |   10 +
 docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md                      |    2 +
 docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md                           |    1 +
 docs/how-to/how-to-use-virtio-mem-with-kata.md                                |    2 +
 src/agent/Cargo.lock                                                          | 4077 ++++++++++++++++++++++++++++++-----
 src/agent/Cargo.toml                                                          |   14 +-
 src/agent/rustjail/src/cgroups/fs/mod.rs                                      |   19 +-
 src/agent/rustjail/src/lib.rs                                                 |    8 +-
 src/agent/src/config.rs                                                       |  220 +-
 src/agent/src/device.rs                                                       |   18 +-
 src/agent/src/image_rpc.rs                                                    |  337 +++
 src/agent/src/main.rs                                                         |    1 +
 src/agent/src/rpc.rs                                                          |  323 ++-
 src/agent/src/sandbox.rs                                                      |    2 +
 src/agent/src/signal.rs                                                       |    2 +-
 src/dragonball/src/api/v1/instance_info.rs                                    |   20 +-
 src/dragonball/src/api/v1/mod.rs                                              |    2 +-
 src/dragonball/src/error.rs                                                   |    4 +
 src/dragonball/src/kvm_context.rs                                             |   47 +-
 src/dragonball/src/vm/mod.rs                                                  |   30 +-
 src/libs/oci/src/lib.rs                                                       |   10 +-
 src/libs/protocols/.gitignore                                                 |    3 +
 src/libs/protocols/build.rs                                                   |   21 +-
 src/libs/protocols/protos/image.proto                                         |   31 +
 src/libs/protocols/src/lib.rs                                                 |    4 +
 src/libs/protocols/src/trans.rs                                               |    4 +-
 src/runtime/Makefile                                                          |  137 ++
 src/runtime/arch/amd64-options.mk                                             |    2 +
 src/runtime/cmd/kata-runtime/kata-check_amd64.go                              |    2 +
 src/runtime/cmd/kata-runtime/kata-check_arm64.go                              |    3 +
 src/runtime/cmd/kata-runtime/kata-check_ppc64le.go                            |    3 +
 src/runtime/cmd/kata-runtime/kata-check_s390x.go                              |    3 +
 src/runtime/config/configuration-clh-tdx.toml.in                              |  443 ++++
 src/runtime/config/configuration-clh.toml.in                                  |    2 +-
 src/runtime/config/configuration-qemu-se.toml.in                              |  673 ++++++
 src/runtime/config/configuration-qemu-sev.toml.in                             |  672 ++++++
 src/runtime/config/configuration-qemu-tdx.toml.in                             |  651 ++++++
 src/runtime/config/configuration-qemu.toml.in                                 |   30 +-
 src/runtime/go.mod                                                            |    3 +-
 src/runtime/go.sum                                                            |  282 +--
 src/runtime/hack/update-generated-hypervisor-proto.sh                         |   13 +
 src/runtime/pkg/README.md                                                     |    1 +
 src/runtime/pkg/containerd-shim-v2/create.go                                  |    5 +
 src/runtime/pkg/containerd-shim-v2/i [...]

2023-03-20 13:34 UTC, Megan-Wright commented
/test

2023-03-20 13:37 UTC, fidencio requested changes
I've left a few comments about the bits that I added to the `main` branch and that shouldn't be considered as part of the `CCv0` one.

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +	install_cached_tarball_component \
... this one ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/scripts/lib.sh
> +	echo "${BUILDER_REGISTRY}:qemu-$(get_last_modification ${qemu_script_dir})-$(uname -m)"
We should keep `CC_BUILDER_REGSTRY` for the `CCv0` branch ...

2023-03-20 13:37 UTC, fidencio commented on tools/packaging/scripts/lib.sh
> +	echo "${BUILDER_REGISTRY}:shim-v2-go-$(get_from_kata_deps "languages.golang.meta.newest-version")-rust-$(get_from_kata_deps "languages.rust.meta.newest-version")-$(get_last_modification ${shim_v2_sc
... the same here ...

2023-03-20 13:52 UTC, Megan-Wright commented
@fidencio thanks for spotting those - updated now!

2023-03-20 13:53 UTC, Megan-Wright commented
/test

2023-03-22 11:11 UTC, fidencio commented
We're hitting a bunch of:
```
11:29:36 warning: spurious network error (2 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1))
11:29:38 warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 1845588 bytes remaining to read)
11:29:46 warning: spurious network error (2 tries remaining): [18] Transferred a partial file (transfer closed with 667659 bytes remaining to read)
11:29:53 warning: spurious network error (2 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1))
11:30:09 warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `libz-sys v1.1.8` failed to transfer more than 10 bytes in 30s)
11:32:43 warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `prost-build v0.10.4` within 30s)
```

I'd like to ignore those and move forward with this PR.

2023-03-27 13:42 UTC, merged