gpu: Build and Ship an GPU enabled Kernel
kata-containers/kata-containers pull request #6581
Opened 2023-04-03 10:12 UTC by zvonkok

With each release make sure we ship a GPU and TEE enabled kernel

Fixes: #6553

2023-04-03 10:16 UTC, zvonkok commented
This kernel can run GPU workloads with SNP,TDX enabled or disabled.

2023-04-03 11:51 UTC, fidencio commented on tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
> +		"-x tdx -g nvidia"
You'll need something like:
```
	local kernel_url="$(get_from_kata_deps assets.kernel-tdx-experimental.url)"

	install_kernel_helper \
		"assets.kernel-tdx-experimental.version" \
		"kernel-tdx-experimental" \
		"-x tdx -u ${kernel_url}"
```

As we pass the `${kernel_url}` here, yq won't be used from inside the nested container.

2023-04-03 11:53 UTC, fidencio requested changes
You'll also need this one:
```
diff --git a/tools/packaging/static-build/kernel/Dockerfile b/tools/packaging/static-build/kernel/Dockerfile
index 4ccf2c0df..34a74a5ee 100644
--- a/tools/packaging/static-build/kernel/Dockerfile
+++ b/tools/packaging/static-build/kernel/Dockerfile
@@ -18,6 +18,7 @@ RUN apt-get update && \
            iptables \
            kmod \
            libelf-dev \
+           libssl-dev \
            patch && \
     if [ "$(uname -m)" = "s390x" ]; then apt-get install -y --no-install-recommends libssl-dev; fi && \
     apt-get clean && rm -rf /var/lib/lists/
```

As building `nvidia` modules requires openssl libraries.

2023-04-04 06:46 UTC, zvonkok commented
I screwed up this one opening a new PR: https://github.com/kata-containers/kata-containers/pull/6595

2023-04-04 06:47 UTC, closed without merging