gha: Enable SEV-SNP tests on main
kata-containers/kata-containers pull request #6810
Opened 2023-05-11 16:00 UTC by fitzthum

Enable SNP tests. I suspect we will need to skip a few tests, but let's see what happens.

2023-05-11 18:33 UTC, fidencio requested changes
Tests passed, yay!

I've left one comment, and I think you could, as a different commit but still part of the same PR, enable the SEV tests as well.

WDYT?

2023-05-11 18:33 UTC, fidencio commented on tests/integration/kubernetes/k8s-cpu-ns.bats
> +	[ "${KATA_HYPERVISOR}" == "qemu-snp" ] && skip "Memory / CPU hotplug support not implemented for SEV-SNP"
Could you extend the conditional and / or use the same message for both TDX / SNP / SEV?

2023-05-11 18:33 UTC, fidencio commented on tests/integration/kubernetes/k8s-cpu-ns.bats
> +	[ "${KATA_HYPERVISOR}" == "qemu-snp" ] && skip "Memory / CPU hotplug support not implemented for SEV-SNP"
Same here.

2023-05-11 18:33 UTC, fidencio commented on tests/integration/kubernetes/k8s-cpu-ns.bats
> +	[ "${KATA_HYPERVISOR}" == "qemu-snp" ] && skip "Memory / CPU hotplug support not implemented for SEV-SNP"
Same here.

2023-05-11 18:33 UTC, fidencio requested changes
Tests passed, yay!

I've left one comment, and I think you could, as a different commit but still part of the same PR, enable the SEV tests as well.

WDYT?

2023-05-11 18:58 UTC, fidencio approved these changes
lgtm, thanks @fitzthum!

2023-05-16 15:59 UTC, fidencio commented
/test

2023-05-16 21:57 UTC, fitzthum commented
Passing with SEV and SNP. Not sure about issue with `run-k8s-tests-on-aks / run-k8s-tests (qemu)`. Is that common? 

Looks like a lot of the Jenkins jobs are getting stuck looking for apt packages.

2023-05-17 06:51 UTC, fidencio commented
> Passing with SEV and SNP. Not sure about issue with `run-k8s-tests-on-aks / run-k8s-tests (qemu)`. Is that common?

Common is a hard word. :-)
It's been flaky and we need to debug that.  Whenever you see those errors, please, open an issue pointing to which test is failing and that will help me to debug it further.

> Looks like a lot of the Jenkins jobs are getting stuck looking for apt packages.

Yeah, Yesterday was not a good day for `apt`.  Let's hope Today it does better.

2023-05-17 06:52 UTC, fidencio commented
/retest

2023-05-17 09:36 UTC, fidencio commented
@fitzthum, I've solved the conflicts, as those were originated by one of my PRs that got merged first, and force-pushed to your branch.

2023-05-17 09:37 UTC, fidencio commented
/test

2023-05-17 10:26 UTC, stevenhorsman approved these changes
LGTM assuming that the tests currently running pass. Thanks @fitzthum

2023-05-17 11:28 UTC, fidencio commented
For the first time, all the tests were executed in the TEEs we support on x86_64. \o/

2023-05-17 13:29 UTC, merged