dragonball: support boot_info.initrd
kata-containers/kata-containers pull request #6920
Opened 2023-05-22 11:36 UTC by ZhangShuaiyi

BootSourceConfig has already support initrd_path, pass boot_info.initrd to BootSourceConfig.initrd_path.

Fixes: #6915

2023-05-24 13:21 UTC, Ji-Xinyou requested changes
One minor problem, others lgtm.

2023-05-24 13:21 UTC, Ji-Xinyou commented on src/libs/kata-types/src/config/hypervisor/dragonball.rs
> +            // if !db.boot_info.initrd.is_empty() {
Remove the segment if you dont want this code.

2023-05-24 13:22 UTC, Ji-Xinyou commented
Also, you need a sign-off for commit message.

2023-05-25 04:46 UTC, ZhangShuaiyi commented
@Ji-Xinyou Done, thanks.

2023-05-25 05:43 UTC, fidencio commented
@ZhangShuaiyi, may I ask you to rebase this PR atop of man? It'll make the CI happier.

2023-05-25 06:12 UTC, ZhangShuaiyi commented
Hi @fidencio, I have ran "git rebase -i main" in my pr branch.  Do my other prs need rebase too?

2023-05-25 07:20 UTC, studychao commented
/test

2023-05-28 16:20 UTC, Ji-Xinyou commented
I close and reopen to rerun the gha and I saw that the failing CI on aks is commonly seen on multiple PRs.

2023-07-11 10:15 UTC, ZhangShuaiyi commented
Hi @Ji-Xinyou  @studychao  @fidencio , please take a look at this. Thanks!

2024-01-15 00:22 UTC, closed without merging