runtime: surpport cold addition vfio for clh
kata-containers/kata-containers pull request #7339
Opened 2023-07-14 02:27 UTC by liangxianlong

In some scenarios, cold addition of vfio network cards is required.

Fixes: #6854

2023-07-17 01:17 UTC, liangxianlong commented
@likebreath

2023-07-17 17:25 UTC, likebreath requested changes
Changes to clh.go looks good to me. One comments below about the unit test.

Also, it would be better to keep using one PR for addressing review comments, so that we all can reference previous conversations. You can always use `git push --force` to override your previous commits.

For the context, this PR is a follow-up of #6856.

2023-07-17 17:25 UTC, likebreath commented on src/runtime/virtcontainers/clh_test.go
> +
I don't think the abstraction of `testCloudHypervisorAddDevice` here is making sense. This function should be removed and everything can be done from `TestCloudHypervisorAddVfioDevice`.

2023-09-18 13:35 UTC, jepio commented
Let's wait to merge this together with https://github.com/kata-containers/kata-containers/pull/7971 which adds a test case of cold-plug vfio.

2024-03-21 06:35 UTC, liangxianlong commented
@liubin

2024-09-25 00:26 UTC, closed without merging