release: Mention the container images used to build the project
kata-containers/kata-containers pull request #7413
Opened 2023-07-21 15:41 UTC by fidencio

This is a small step towards build reproducibility.

Fixes: #7412

2023-07-21 16:02 UTC, fidencio commented
/test

2023-07-21 19:01 UTC, dborquez requested changes

2023-07-21 19:01 UTC, dborquez commented on tools/packaging/release/release-notes.sh
> +The users who want to rebuild the tarballs using exactly the same images can simly use the following environment
```suggestion
The users who want to rebuild the tarballs using exactly the same images can simply use the following environment
```

2023-07-24 16:02 UTC, fidencio commented on tools/packaging/release/release-notes.sh
> +The users who want to rebuild the tarballs using exactly the same images can simly use the following environment
Fixed, thanks!

2023-07-24 16:02 UTC, fidencio commented
/test

2023-07-24 17:10 UTC, GabyCT approved these changes

2023-07-24 21:46 UTC, dborquez approved these changes

2023-07-24 21:46 UTC, merged