metrics: Add sysbench performance test
kata-containers/kata-containers pull request #7486
Opened 2023-07-28 19:55 UTC by GabyCT

This PR adds the sysbench performance test for kata CI.

Fixes #7485

2023-07-29 00:51 UTC, cmaf approved these changes
thanks @GabyCT

2023-07-31 17:02 UTC, GabyCT commented
/test

2023-07-31 20:26 UTC, dborquez requested changes

2023-07-31 20:26 UTC, dborquez commented on tests/metrics/density/k8s-sysbench.sh
> +
Please remove empty line

2023-07-31 20:29 UTC, GabyCT commented on tests/metrics/density/k8s-sysbench.sh
> +
@dborquez changes applied thanks

2023-07-31 20:29 UTC, dborquez approved these changes
LGTM, thank you @GabyCT

2023-07-31 20:29 UTC, dborquez commented
/test

2023-07-31 20:31 UTC, GabyCT commented
/test

2023-07-31 23:14 UTC, GabyCT commented
/test-ubuntu

2023-07-31 23:14 UTC, GabyCT commented
/test-clh-devmapper

2023-07-31 23:14 UTC, GabyCT commented
/test-devmapper

2023-08-01 16:17 UTC, merged