metrics: Add common functions to the common script
kata-containers/kata-containers pull request #7618
Opened 2023-08-10 17:28 UTC by GabyCT

This PR adds the collect results function to the common metrics script.

Fixes #7617

2023-08-10 17:53 UTC, dborquez requested changes
LGTM in general.

2023-08-10 17:53 UTC, dborquez commented on tests/metrics/lib/common.bash
> +	local tasks_running=("${containers[@]}")
@GabyCT I think you should pass the variable `containers[@]` to this function.

2023-08-10 20:01 UTC, dborquez approved these changes
@GabyCT LGTM, thank you

2023-08-10 20:25 UTC, GabyCT commented
/test

2023-08-14 18:05 UTC, cmaf approved these changes
thanks @GabyCT

2023-08-14 20:22 UTC, merged