packaging: qemu-snp-experimental: support host kernel with gmem
kata-containers/kata-containers pull request #9086
Opened 2024-02-13 16:15 UTC by niteeshkd

This is required to allow creation of SNP coco on host kernel (e.g. https://github.com/AMDESE/linux ,branch:snp-host-latest) supporting guest private memory for SNP using gmem.

2024-02-13 16:16 UTC, niteeshkd commented
@ryansavino @fitzthum @fidencio

2024-02-13 17:05 UTC, fidencio commented
@niteeshkd, does it require any change in the QEMU command line used to create the VM?

2024-02-13 17:50 UTC, niteeshkd commented
> does it require any change in the QEMU command line used to create the VM?

It does not require change in the kata shim to create the SNP coco. If we need to handle the attestation, we will have to modify the shim which we will handle later.

2024-02-13 17:57 UTC, fidencio commented
I'll leave the review for those more familiar with those changes, and if an ack is needed from my side, I'll add after they do the review.
Thanks @niteeshkd!

2024-02-13 18:34 UTC, fitzthum approved these changes
Looks good. We'll want to make sure to run to upgrade the CI nodes.

Btw @niteeshkd will this new QEMU still function on the old non-UPM SNP Kernel? If not we should probably also add a note to the coco docs.

Also @danmihai1 might be interested.

2024-02-13 18:47 UTC, niteeshkd commented
> Btw @niteeshkd will this new QEMU still function on the old non-UPM SNP Kernel? If not we should probably also add a note to the coco docs.

No, this qemu on non-UPM kernel does not work.  Here is the error it reports.
```
$ sudo journalctl -xeu containerd
...
 Feb 13 18:41:04 amdmilan1 kata[4163390]: time="2024-02-13T18:41:04.079527912Z" level=error msg="qemu-system-x86_64: vm-type snp not supported by KVM"
```

2024-02-13 19:08 UTC, fitzthum commented
> No, this qemu on non-UPM kernel does not work. Here is the error it reports.

Ok, we'll just have to be clear that we have a change of host requirements for the next release.

2024-02-13 19:09 UTC, fitzthum commented
Also @zvonkok might be interested in this?

2024-02-13 21:17 UTC, fidencio commented
> No, this qemu on non-UPM kernel does not work. Here is the error it reports.

Please, add this to the commit message. :-)

2024-02-13 22:55 UTC, ryansavino commented
/test

2024-02-15 16:14 UTC, niteeshkd commented
Fixed building of qemu-snp-experimental using tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh .

2024-02-15 16:30 UTC, ryansavino requested changes

2024-02-15 16:30 UTC, ryansavino commented on tools/packaging/static-build/qemu/Dockerfile
> +	    rsync\
Can we re-add the space here?

2024-02-15 17:16 UTC, ryansavino approved these changes

2024-02-15 18:24 UTC, fidencio commented
/test

2024-02-15 18:25 UTC, fidencio approved these changes
lgtm, thanks @niteeshkd!

2024-02-19 16:50 UTC, merged