runtime: enable kernel-hashes for SNP confidential container
kata-containers/kata-containers pull request #9151
Opened 2024-02-23 21:16 UTC by niteeshkd

This is required to provide the hashes of kernel, initrd and cmdline needed during the attestation of the coco.

Fixes: #9150

2024-02-23 21:17 UTC, niteeshkd commented
@ryansavino @fitzthum @fidencio

2024-02-24 12:45 UTC, fidencio commented on versions.yaml
> +      version: "edk2-stable202402"
Just one comment here.  It seems we can use stable edk2 pretty much evrywhere, as that has support for SEV / SNP / TDX.

Would it be possible to actually keep the versions of those aligned?

2024-02-25 11:47 UTC, zvonkok commented
/cc @zvonkok

2024-02-28 22:43 UTC, ryansavino requested changes

2024-02-29 16:09 UTC, niteeshkd commented on versions.yaml
> -      version: "edk2-stable202302"
@ryansavino , I have created different commit for upgrading ovmf.

2024-02-29 16:48 UTC, ryansavino approved these changes

2024-02-29 18:39 UTC, fitzthum approved these changes

2024-03-13 20:42 UTC, fitzthum commented
Hm can we get another pair of eyes here? Maybe @stevenhorsman  or @danmihai1?

2024-03-14 10:38 UTC, stevenhorsman commented
/test

2024-03-14 14:35 UTC, stevenhorsman commented
I tried re-running the SNP tests on this and they seem to be failing (compared to the last nightly that was successful), so I'd like to see that pass for this PR before approving. Thanks

2024-03-14 15:18 UTC, danmihai1 commented
> Hm can we get another pair of eyes here? Maybe @stevenhorsman or @danmihai1?

@fitzthum , thanks for the heads-up! However, I am not knowledgeable enough about kernel hashes to be able to help much here. In AKS, we load linux in the Guest VM using IGVM files and related ways of verifying the integrity of the boot chain.

2024-04-11 16:14 UTC, ryansavino commented
/test

2024-04-11 23:02 UTC, ryansavino commented
All checks and required tests passing.

2024-04-12 13:23 UTC, fitzthum commented
SNP is failing again

2024-06-07 15:11 UTC, ryansavino commented
This PR is ready to go. Required tests passing. Tapping @fidencio @stevenhorsman @wainersm @danmihai1 for review. Thanks!

2024-06-07 16:01 UTC, wainersm approved these changes
Thanks!

2024-06-07 16:16 UTC, fidencio commented on versions.yaml
> +      version: "edk2-stable202402"
We're not relying on our Kata Containers packaged OVMF for TDX, but rather on what the distros are providing.  IOW, TDX is not affected by this change.

2024-06-07 23:19 UTC, merged