gha: Add cloud-hypervisor (runtime-rs) support to cri-containerd tests
kata-containers/kata-containers pull request #9182
Opened 2024-02-28 19:26 UTC by GabyCT

This PR adds the Cloud Hypervisor driver, integrated with the runtime-rs, as part of the cri-containerd tests.

Fixes #9181

2024-02-28 22:22 UTC, GabyCT commented
/test

2024-02-29 15:41 UTC, amshinde approved these changes

2024-02-29 17:51 UTC, dborquez requested changes
LGTM but I leave a few comments.

2024-02-29 17:51 UTC, dborquez commented on tests/integration/cri-containerd/gha-run.sh
> +		install_"${dep[0]}" "${dep[1]}"
Here you could enclose the entire word using double quotes:
```suggestion
		"install_${dep[0]}" "${dep[1]}"
```

2024-02-29 17:51 UTC, dborquez commented on tests/integration/cri-containerd/gha-run.sh
> +	"${repo_root_dir}"/tests/install_go.sh -p -f
You could enclose the path and the command using double quotes, and call it with the source command (which is an alias for `.` )
```suggestion
	. "${repo_root_dir}/tests/install_go.sh" -p -f
```

2024-02-29 18:17 UTC, dborquez approved these changes
LGTM thank you @GabyCT

2024-02-29 18:20 UTC, GabyCT commented
/test

2024-02-29 20:12 UTC, merged