runtime-rs: Add RTC to QEMU cmdline
kata-containers/kata-containers pull request #9519
Opened 2024-04-18 19:12 UTC by emanuellima1

WiP, still missing implementation on the QemuCmdLine struct

Signed-off-by: Emanuel Lima <emlima@redhat.com>

2024-04-19 13:29 UTC, pmores commented on src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
> +        params.push("rtc".to_owned());
This line should be dropped.  What this function need to output is along the lines of
`-rtc base=utc,driftfix=slew,clock=host`
but as is, the output would apparently be more like
`-rtc rtc,base=utc,driftfix=slew,clock=host`

2024-04-22 16:45 UTC, gkurz requested changes
Hi @emanuellima1 ! Thanks for working on this.

The PR currently adds the generation code for `-rtc`. Now you need to have this code called from the `build()` function.

2024-04-22 16:45 UTC, gkurz commented on src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
> +    fn new(base: &str, clock: &str, driftfix: &str) -> Rtc {
RTC isn't user configurable. The command line we want is exactly `-rtc base=utc,driftfix=slew,clock=host`.
I suggest you drop the arguments to this functions and you just hard-code the values in the `Rtc` instance below.

2024-04-23 07:30 UTC, gkurz commented
>  Fix conversations

Pushing a fix commit definitely allows to clearly track changes requested by reviewers, but this is pretty much the only advantage. In the end we wan't these fixes to be squashed into the original commit since we just want to record the version that final result, not the intermediary steps induced by the review. And also this will make the `commit message check` happy since it mandates all commits to have a proper SoB tag.

Since you've addressed @pmores 's suggestions, I suggest you squash the `Fix converstations` commit into `runtime-rs: Add RTC to QEMU cmdline`. You should then process my requests and likely squash these changes into the same commit. And then you can force push to the PR.

2024-04-23 12:17 UTC, emanuellima1 commented
> > Fix conversations
> 
> Pushing a fix commit definitely allows to clearly track changes requested by reviewers, but this is pretty much the only advantage. In the end we wan't these fixes to be squashed into the original commit since we just want to record the version that final result, not the intermediary steps induced by the review. And also this will make the `commit message check` happy since it mandates all commits to have a proper SoB tag.
> 
> Since you've addressed @pmores 's suggestions, I suggest you squash the `Fix converstations` commit into `runtime-rs: Add RTC to QEMU cmdline`. You should then process my requests and likely squash these changes into the same commit. And then you can force push to the PR.

I thought that I could squash when the PR was merged, like I do in Gitlab, but I can do it now too.

2024-04-23 13:12 UTC, gkurz commented
> I thought that I could squash when the PR was merged, like I do in Gitlab, but I can do it now too.

This works as well but you'll need all the commits to be properly formatted in order to pass the required commit check CI otherwise the PR won't be mergeable.

Please see https://github.com/kata-containers/kata-containers/actions/runs/8755034747/job/24033016362?pr=9519 .

2024-04-23 14:16 UTC, gkurz approved these changes
LGTM and I could verify that this PR does add ` -rtc base=utc,driftfix=slew,clock=host` on the QEMU command line. Thanks @emanuellima1 !

2024-04-23 14:18 UTC, gkurz commented
/test

2024-04-26 08:27 UTC, Apokleos approved these changes
Thx @emanuellima1 for your contribution! 
but no related issue or Fixes #xxx the CI is also happy ? @gkurz 

anyway LGTM !

2024-04-26 08:47 UTC, gkurz commented
> Thx @emanuellima1 for your contribution! but no related issue or Fixes #xxx the CI is also happy ? @gkurz
> 

@Apokleos yes, this era is over :tada: . See #9501 .

2024-04-26 09:43 UTC, Apokleos commented
> > Thx @emanuellima1 for your contribution! but no related issue or Fixes #xxx the CI is also happy ? @gkurz
> 
> @Apokleos yes, this era is over 🎉 . See #9501 .
>
Yeah, It's over !

2024-04-26 09:44 UTC, merged