genpolicy: add support for runAsUser
kata-containers/kata-containers pull request #9578
Opened 2024-04-30 22:34 UTC by Redent0r

Add policy support for SecurityContext and PodSecurityContext runAsUser.

Also, remove outdated UID rule workaround.

Fixes: #8879

2024-07-01 20:22 UTC, wainersm commented
Hi @Redent0r !

Could you please split this in 2 commits: one for the PodSecurityContext piece and other for the UID stuff. The former I did understand, while the later I haven't enough context for judging. Could you provider more information (in form of commit message)?

2024-07-12 23:23 UTC, danmihai1 requested changes
I have just noticed that the image ghcr.io/oracle/oci-cli might still need the old workaround for "p_user.UID == i_user.UID". So, let's investigate this new issue before merging this PR.

2024-07-12 23:50 UTC, danmihai1 commented
Yep, ghcr.io/oracle/oci-cli still requires the workaround being removed here. So, let's close this PR and rethink it.

genpolicy doesn't handle ghcr.io/oracle/oci-cli correctly due to https://github.com/kata-containers/kata-containers/issues/9928.

2024-07-12 23:50 UTC, closed without merging

2024-07-15 16:12 UTC, danmihai1 commented
This PR has been replaced by: https://github.com/kata-containers/kata-containers/pull/10008