runtime: Enable connection to Quote Generation Service (QGS)
kata-containers/kata-containers pull request #9653
Opened 2024-05-17 06:49 UTC by JakubLedworowski

For the TD attestation to work the connection to QGS on the host is needed. By default QGS runs on vsock port 4050, but can be modified by the host owner. Format of the qemu object follows the SocketAddress structure, so it needs to be provided in the JSON format, as in the example below: -object '{"qom-type":"tdx-guest","id":"tdx","quote-generation-socket":{"type":"vsock","cid":"2","port":"4050"}}'

Fixes: #9497

2024-05-20 09:31 UTC, fidencio commented
I am setting this to "Ready to Review"  as I was able to check that both Ubuntu and CentOS are using exactly the very same command line for QEMU, which is great, and avoids us to do any kind of distro check on the runtime side.

2024-05-20 09:33 UTC, fidencio requested changes
I've left one comment, apart from the comment, everything looks good, thanks @JakubLedworowski!

2024-05-20 09:33 UTC, fidencio commented on src/runtime/pkg/govmm/qemu/qemu.go
> +	"github.com/kata-containers/kata-containers/src/runtime/pkg/device/api"
I noticed that you're only using this for logging purposes.
Please, use `log`, which is already imported here, instead of importing a new package.

2024-05-20 14:21 UTC, fidencio commented
/test

2024-05-22 12:17 UTC, fidencio approved these changes
@JakubLedworowski, very nice work, thanks, and lgtm!

2024-05-22 12:17 UTC, fidencio commented
/test

2024-05-22 13:45 UTC, chavafg approved these changes

2024-05-22 13:49 UTC, merged