genpolicy: add ability to filter for runtimeClassName
kata-containers/kata-containers pull request #9725
Opened 2024-05-27 21:48 UTC by 3u13r

Add a command line flag to the genpolicy tool. 
The given value ("kata-cc" by default) must match the `runtimeClassName` of K8s resources which have this field defined (even if not explicitly set) like Deployment, DaemonSet, ReplicaSet,...

This is useful when the policies for a more complex deployment should be generated. Before, a policy would be attached on e.g. every pod even if it wasn't supposed to run as a confidential container. Additionally, to be able to generate that policy, the container needed to be downloaded which, depending on the size, might take some time. 

I choose using the given parameter value as a prefix, because in Contrast we have our own runtimeClassName `contrast-cc-<sha265sum indicating the version>` for which we don't want to carry around the full value all the time.
Another option I thought about, was to implement the ability to match via a glob pattern.

cc: @danmihai1 

Fixes: https://github.com/kata-containers/kata-containers/issues/8571

2024-05-28 17:41 UTC, danmihai1 commented
@3u13r this looks pretty good to me - I've added a couple of comments. 

Please add some CI test cases to this PR. Some examples:

https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-policy-job.bats
https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-policy-pod.bats
https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-policy-rc.bats

2024-05-28 17:42 UTC, danmihai1 requested changes

2024-05-28 17:42 UTC, danmihai1 commented on src/tools/genpolicy/src/utils.rs
> +    runtime_class_name: Option<String>,
@3u13r please look into supporting multiple runtime_class_names here - just in case users will need more than one in the future.

2024-05-28 17:42 UTC, danmihai1 commented on src/tools/genpolicy/src/utils.rs
> +        default_missing_value = "kata-cc", // used if flag is present but no value is given
Please remove this default value - if I understand correctly, that's not a commonly name used in Kata CI, etc.

2024-05-30 00:16 UTC, 3u13r commented
Thanks for the feedback. Tried to address the comments. Not sure if we want to integrate the test into the current pod test (see the current proposal) or if we already want another test file.

2024-05-30 00:21 UTC, danmihai1 commented
Thanks @3u13r! The changes seem good to me at a quick look. I will start the CI tests.

2024-05-30 00:56 UTC, 3u13r commented
Added the CI feedback (not needed return statement, commit message, commit sign-off)

2024-05-30 14:39 UTC, danmihai1 commented
@3u13r, it looks like the test needs to create my-runtime-class:

https://github.com/kata-containers/kata-containers/actions/runs/9295620216/job/25583406707?pr=9725

```
2024-05-30T02:26:19.5742759Z not ok 2 Successful pod with auto-generated policy and runtimeClassName filter
2024-05-30T02:26:19.5750699Z # (in test file k8s-policy-pod.bats, line 65)
2024-05-30T02:26:19.5760915Z #   `kubectl create -f "${testcase_pre_generate_pod_yaml}"' failed
2024-05-30T02:26:19.5769119Z # [bats-exec-test:59] INFO: k8s configured to use runtimeclass
2024-05-30T02:26:19.5783638Z # [bats-exec-test:191] INFO: Executing: RUST_LOG=info /opt/kata/bin/genpolicy -u -y /home/runner/work/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/k8s-policy-pod-testcase-pre-generation.yaml -p /home/runner/work/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/rules.rego -j /home/runner/work/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/genpolicy-settings.json -c /home/runner/work/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/k8s-policy-configmap-testcase-pre-generation.yaml --runtime-class-names=other-runtime-class-name --runtime-class-names=my-runtime-class
2024-05-30T02:26:19.5790739Z # [2024-05-30T02:26:16Z INFO  genpolicy::registry] ============================================
2024-05-30T02:26:19.5792134Z # [2024-05-30T02:26:16Z INFO  genpolicy::registry] Pulling manifest and config for "quay.io/prometheus/busybox:latest"
2024-05-30T02:26:19.5792994Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] Using cache file
2024-05-30T02:26:19.5793978Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] dm-verity root hash: 2e52d86498030b4b99318650826d3f121bdfac5fe7bbbea9d18c546d48003aa0
2024-05-30T02:26:19.5794970Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] Using cache file
2024-05-30T02:26:19.5796005Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] dm-verity root hash: 75ed5e78d30374b9557d32c17ae6d2e1b4afdc5efd128812e6c99a0f60708dba
2024-05-30T02:26:19.5797286Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] ============================================
2024-05-30T02:26:19.5798635Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] Pulling manifest and config for "mcr.microsoft.com/oss/kubernetes/pause:3.6"
2024-05-30T02:26:19.5799634Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] Using cache file
2024-05-30T02:26:19.5801426Z # [2024-05-30T02:26:17Z INFO  genpolicy::registry] dm-verity root hash: 817250f1a3e336da76f5bd3fa784e1b26d959b9c131876815ba2604048b70c18
2024-05-30T02:26:19.5803005Z # [2024-05-30T02:26:17Z INFO  genpolicy] Success!
2024-05-30T02:26:19.5803899Z # configmap/policy-configmap created
2024-05-30T02:26:19.5806072Z # Error from server (Forbidden): error when creating "/home/runner/work/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/k8s-policy-pod-testcase-pre-generation.yaml": pods "policy-pod" is forbidden: pod rejected: RuntimeClass "my-runtime-class" not found
```

2024-05-30 22:12 UTC, 3u13r commented
Fixed the behavior when no `--runtime-class-names` is given (disabling all filtering instead of filtering out _all_ resources).
Also made the loop a bit more concise.
(Tried to) fix the test by simply reading the existing `runtimeClassName` from the yaml.

2024-05-30 23:47 UTC, 3u13r commented
Tried to fix the second test (https://github.com/kata-containers/kata-containers/actions/runs/9309837918/job/25626890911?pr=9725) by using [bats  "run !"](https://bats-core.readthedocs.io/en/stable/gotchas.html#my-negated-statement-e-g-true-does-not-fail-the-test-even-when-it-should). 
Also fixed the formatting issue.

2024-05-31 01:19 UTC, 3u13r commented
Sorry that this takes to long. 

Removed the `short` CLI option for `--runtime-class-names` since it clashed with the short version for `--raw-out`.

2nd attempt fixing https://github.com/kata-containers/kata-containers/actions/runs/9310632801/job/25628898963?pr=9725:
Save one pre-generated files just once before generation, since afterwards those files already have generated content in them.

2024-05-31 19:03 UTC, 3u13r commented
As far as I can tell, my test are working now. Are the other tests flaky?

2024-05-31 19:39 UTC, danmihai1 commented
> As far as I can tell, my test are working now. Are the other tests flaky?

Indeed, the cbl-mariner tests (e.g., https://github.com/kata-containers/kata-containers/actions/runs/9311427811/job/25631015332?pr=9725) succeeded. (Sadly, just cbl-mariner tests genpolicy at this point - we'd like to add more platforms.)

Yes, other tests are expected to fail sometimes. I will retry to see if we can get more of them to pass.

2024-05-31 19:41 UTC, danmihai1 approved these changes

2024-06-04 16:05 UTC, GabyCT approved these changes

2024-06-04 16:06 UTC, merged