tests: Increase timeout to crictl calls on kata monitor tests
kata-containers/kata-containers pull request #9897
Opened 2024-06-24 20:08 UTC by GabyCT

This PR increases the timeout to crictl calls on kata monitor tests to avoid to hit issues every now and avoid random failures. This PR is very similar to PR #7640.

2024-06-24 23:35 UTC, danmihai1 approved these changes

2024-06-25 22:25 UTC, dborquez requested changes
Because the assigned timeout is the same in all cases, could you set a timeout using a variable?

2024-06-25 22:25 UTC, dborquez commented on tests/functional/kata-monitor/kata-monitor-tests.sh
> +	POD_ID=$(sudo crictl --timeout=20s runp $args $sbfile)
```suggestion
	POD_ID=$(sudo crictl --timeout=${TO} runp $args $sbfile)
```

2024-06-25 22:25 UTC, dborquez commented on tests/functional/kata-monitor/kata-monitor-tests.sh
readonly TO="20s"

2024-06-25 22:43 UTC, dborquez approved these changes
LGTM, thanks @GabyCT

2024-06-25 23:27 UTC, merged